version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_agents_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/data_agents_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - AGENT_API_URL=http://localhost:5678/api/v1
      - AGENT_API_KEY=your-api-key-here

  # You can uncomment this if you want to use n8n as the agent backend
  # n8n:
  #   image: n8nio/n8n
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=http
  #     - N8N_HOST=localhost
  #     - DB_TYPE=postgresdb
  #     - DB_POSTGRESDB_HOST=postgres
  #     - DB_POSTGRESDB_PORT=5432
  #     - DB_POSTGRESDB_DATABASE=n8n
  #     - DB_POSTGRESDB_USER=postgres
  #     - DB_POSTGRESDB_PASSWORD=postgres
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  # n8n_data: